In [1]:
#Given an nxn grid of points with weight associated to each one of them this function distributes each weight to the neighboring corners of the cells

In [2]:
import numpy as np
import math

In [5]:
#size of the data
n = 5
#Create random data
data_lattice = np.random.randint(10, size=(n, n))

In [6]:
data_lattice

array([[2, 5, 4, 6, 2],
       [0, 9, 8, 9, 4],
       [6, 2, 5, 1, 4],
       [5, 0, 7, 1, 9],
       [5, 9, 7, 9, 1]])

In [7]:
data_lattice[1][0]

0

In [157]:
data_lattice_distribution = data_lattice.astype(float)/4
weight = np.copy(data_lattice_distribution)
weight

array([[ 0.5 ,  1.25,  1.  ,  1.5 ,  0.5 ],
       [ 0.  ,  2.25,  2.  ,  2.25,  1.  ],
       [ 1.5 ,  0.5 ,  1.25,  0.25,  1.  ],
       [ 1.25,  0.  ,  1.75,  0.25,  2.25],
       [ 1.25,  2.25,  1.75,  2.25,  0.25]])

In [158]:

for j in range (0,n):
    for i in range(0,n):
        if (i != n-1):
            data_lattice_distribution[i+1][j] = data_lattice_distribution[i+1][j] + weight[i][j]
        if ( j != 0 and i!= n-1):
            data_lattice_distribution[i+1][j-1] = data_lattice_distribution[i+1][j-1] + weight[i][j]
        if (j != 0):
            data_lattice_distribution[i][j-1] = data_lattice_distribution[i][j-1] + weight[i][j]
        

In [159]:
data_lattice_distribution

array([[ 1.75,  2.25,  2.5 ,  2.  ,  0.5 ],
       [ 4.  ,  6.5 ,  6.75,  5.25,  1.5 ],
       [ 4.25,  6.  ,  5.75,  4.5 ,  2.  ],
       [ 3.25,  3.5 ,  3.5 ,  3.75,  3.25],
       [ 4.75,  5.75,  6.  ,  5.  ,  2.5 ]])

In [165]:
int(math.sqrt(data_lattice_distribution.size))

5